### ISSUE TITLE
Constant error

### ISSUE THREAD

**Issue by maquejp** [vscode-restructuredtext/snooty-parser#11]
Hello,

I have this error in the OUTPUT (Snooty Language Client) can you help me about it?

I am on OSX (BigSur 11.1)

Thank you.

`
WARNING:pyls_jsonrpc.endpoint:Ignoring notification for unknown method textDocument/didSave
WARNING:pyls_jsonrpc.endpoint:Ignoring notification for unknown method workspace/didChangeWatchedFiles
ERROR:pyls_jsonrpc.endpoint:Failed to handle request 238
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 424, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 402, in completions
    line_content = self.project.get_line_content(filePath, position["line"])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1433, in get_line_content
    return self._project.get_line_content(path, position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1149, in get_line_content
    page = self.pages[fileid]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1008, in __getitem__
    return self.__postprocessed[key]
KeyError: FileId('docs/source/Starting-with-the-API.rest')
[Error - 5:26:01 PM] Request textDocument/completion failed.
  Message: KeyError: FileId('docs/source/Starting-with-the-API.rest')
  Code: -32602 
[object Object]
ERROR:pyls_jsonrpc.endpoint:Failed to handle request 239
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 424, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 402, in completions
    line_content = self.project.get_line_content(filePath, position["line"])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1433, in get_line_content
    return self._project.get_line_content(path, position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1149, in get_line_content
    page = self.pages[fileid]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1008, in __getitem__
    return self.__postprocessed[key]
KeyError: FileId('docs/source/Starting-with-the-API.rest')
[Error - 5:26:01 PM] Request textDocument/completion failed.
  Message: KeyError: FileId('docs/source/Starting-with-the-API.rest')
  Code: -32602 
[object Object]
ERROR:pyls_jsonrpc.endpoint:Failed to handle request 240
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 424, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 402, in completions
    line_content = self.project.get_line_content(filePath, position["line"])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1433, in get_line_content
    return self._project.get_line_content(path, position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1149, in get_line_content
    page = self.pages[fileid]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1008, in __getitem__
    return self.__postprocessed[key]
KeyError: FileId('docs/source/Starting-with-the-API.rest')
[Error - 5:26:02 PM] Request textDocument/completion failed.
  Message: KeyError: FileId('docs/source/Starting-with-the-API.rest')
  Code: -32602 
[object Object]
ERROR:pyls_jsonrpc.endpoint:Failed to handle request 241
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 424, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 402, in completions
    line_content = self.project.get_line_content(filePath, position["line"])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1433, in get_line_content
    return self._project.get_line_content(path, position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1149, in get_line_content
    page = self.pages[fileid]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1008, in __getitem__
    return self.__postprocessed[key]
KeyError: FileId('docs/source/Starting-with-the-API.rest')
[Error - 5:26:02 PM] Request textDocument/completion failed.
  Message: KeyError: FileId('docs/source/Starting-with-the-API.rest')
  Code: -32602 
[object Object]
ERROR:pyls_jsonrpc.endpoint:Failed to handle request 242
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 424, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 402, in completions
    line_content = self.project.get_line_content(filePath, position["line"])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1433, in get_line_content
    return self._project.get_line_content(path, position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1149, in get_line_content
    page = self.pages[fileid]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1008, in __getitem__
    return self.__postprocessed[key]
KeyError: FileId('docs/source/Starting-with-the-API.rest')
[Error - 5:26:02 PM] Request textDocument/completion failed.
  Message: KeyError: FileId('docs/source/Starting-with-the-API.rest')
  Code: -32602 
[object Object]
ERROR:pyls_jsonrpc.endpoint:Failed to handle request 243
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 424, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 402, in completions
    line_content = self.project.get_line_content(filePath, position["line"])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1433, in get_line_content
    return self._project.get_line_content(path, position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1149, in get_line_content
    page = self.pages[fileid]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1008, in __getitem__
    return self.__postprocessed[key]
KeyError: FileId('docs/source/Starting-with-the-API.rest')
[Error - 5:26:02 PM] Request textDocument/completion failed.
  Message: KeyError: FileId('docs/source/Starting-with-the-API.rest')
  Code: -32602 
[object Object]
ERROR:pyls_jsonrpc.endpoint:Failed to handle request 244
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 424, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/language_server.py", line 402, in completions
    line_content = self.project.get_line_content(filePath, position["line"])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1433, in get_line_content
    return self._project.get_line_content(path, position)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1149, in get_line_content
    page = self.pages[fileid]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snooty/parser.py", line 1008, in __getitem__
    return self.__postprocessed[key]
KeyError: FileId('docs/source/Starting-with-the-API.rest')
[Error - 5:26:03 PM] Request textDocument/completion failed.
  Message: KeyError: FileId('docs/source/Starting-with-the-API.rest')
  Code: -32602 
[object Object]
WARNING:pyls_jsonrpc.endpoint:Ignoring notification for unknown method textDocument/didSave
WARNING:pyls_jsonrpc.endpoint:Ignoring notification for unknown method workspace/didChangeWatchedFiles

`

**Comment by lextm** [comment]
Can you verify that this issue remains even in latest snooty release?
