### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by stonecharioteer** [vscode-restructuredtext/snooty-parser#19]
I've been trying to use the RestructuredText plugin for VS Code and for some reason, I constantly get the following errors:

```
ERROR:pyls_jsonrpc.endpoint:Failed to handle request 292
Traceback (most recent call last):
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/snooty/language_server.py", line 450, in m_text_document__completion
    return self.completions(textDocument["uri"], position)
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/snooty/language_server.py", line 418, in completions
    line_content = self.project.get_line_content(filePath, position["line"])
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/snooty/parser.py", line 1530, in get_line_content
    return self._project.get_line_content(path, line)
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/snooty/parser.py", line 1219, in get_line_content
    return lines[line]
IndexError: list index out of range
[Error - 6:56:17 pm] Request textDocument/completion failed.
  Message: IndexError: list index out of range
  Code: -32602 
[object Object]
ERROR:pyls_jsonrpc.endpoint:Failed to handle request 293
Traceback (most recent call last):
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/snooty/language_server.py", line 450, in m_text_document__completion
    return self.completions(textDocument["uri"], position)
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/snooty/language_server.py", line 418, in completions
    line_content = self.project.get_line_content(filePath, position["line"])
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/snooty/parser.py", line 1530, in get_line_content
    return self._project.get_line_content(path, line)
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/snooty/parser.py", line 1219, in get_line_content
    return lines[line]
IndexError: list index out of range
[Error - 6:56:22 pm] Request textDocument/completion failed.
  Message: IndexError: list index out of range
  Code: -32602 
[object Object]
WARNING:pyls_jsonrpc.endpoint:Ignoring notification for unknown method textDocument/didSave
WARNING:pyls_jsonrpc.endpoint:Ignoring notification for unknown method workspace/didChangeWatchedFiles
ERROR:pyls_jsonrpc.endpoint:Failed to handle request 309
Traceback (most recent call last):
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/snooty/language_server.py", line 450, in m_text_document__completion
    return self.completions(textDocument["uri"], position)
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/snooty/language_server.py", line 418, in completions
    line_content = self.project.get_line_content(filePath, position["line"])
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/snooty/parser.py", line 1530, in get_line_content
    return self._project.get_line_content(path, line)
  File "/home/stonecharioteer/code/tools/anaconda3/envs/sphinx/lib/python3.9/site-packages/snooty/parser.py", line 1219, in get_line_content
    return lines[line]
IndexError: list index out of range
[Error - 6:56:39 pm] Request textDocument/completion failed.
  Message: IndexError: list index out of range
  Code: -32602 
```

I have it installed inside a Python 3.9 Conda Environment that has sphinx also installed. Is there something I've messed up in my environment?

**Comment by lextm** [comment]
Duplicate to #20 

If you update the VSCode extension to the latest, it will guide you to upgrade snooty to the correct version.
