### ISSUE TITLE
UnicodeDecodeError Opening Project

### ISSUE THREAD

**Issue by lbussy** [vscode-restructuredtext/snooty-parser#25]
When I open my PlatformIO project in VSCode, I get:

```
A request has failed.  See the output for more information.
Source: reStructruredText (Extension)
```

Checking the output gives:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 37: invalid start byte
Source: reStructruredText (Extension)
```

![image](https://user-images.githubusercontent.com/9092188/120890236-e28cb200-c5c6-11eb-92b9-5e185c806e0f.png)

This occurs if I have any `*.rst` files in my docs directory, even blanks files.  Thinking I had something strange in my conf.py, I deleted everything there and initialized a new project with Sphinx.  I get the same issue.

The tree looks like:

```
docs
├───_build
├───_static
└───_templates
```
 
My `conf.py` consists of:

``` python
project = 'Test Project'
copyright = '2021, Lee C. Bussy'
author = 'Lee C. Bussy'

release = '0.0.1'

extensions = [
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
html_theme = 'alabaster'
html_static_path = ['_static']
```

I'm at a bit of a loss, I'm not sure if there's any other output or logging I can check.  I'm definitely beyond frustrated, having completely wiped and re-reated my dev environment twice now.

**Comment by lbussy** [comment]
I'm not sure how (I can't reproduce it) but I did manage to capture an assertion:

``` python3
INFO:snooty.main:Snooty 1.9.2.dev0 starting
INFO:snooty.language_server:Started
INFO:snooty.parser:git error getting branch name: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

ERROR:pyls_jsonrpc.endpoint:Failed to handle request 0
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\********\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\********\AppData\Roaming\Python\Python39\site-packages\snooty\parser.py", line 978, in parse_rst
    visitor, text = parser.parse(path, text)
  File "C:\Users\********\AppData\Roaming\Python\Python39\site-packages\snooty\rstparser.py", line 1211, in parse
    text, diagnostics = self.project_config.read(path, text)
  File "C:\Users\********\AppData\Roaming\Python\Python39\site-packages\snooty\types.py", line 190, in read
    text = path.read_text(encoding="utf-8")
  File "C:\Users\********\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1257, in read_text
    return f.read()
  File "C:\Users\********\AppData\Local\Programs\Python\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 37: invalid start byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\********\AppData\Roaming\Python\Python39\site-packages\pyls_jsonrpc\endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "C:\Users\********\AppData\Roaming\Python\Python39\site-packages\pyls_jsonrpc\endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "C:\Users\********\AppData\Roaming\Python\Python39\site-packages\pyls_jsonrpc\dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "C:\Users\********\AppData\Roaming\Python\Python39\site-packages\snooty\language_server.py", line 372, in m_initialize
    self.project.build(postprocess=False)
  File "C:\Users\********\AppData\Roaming\Python\Python39\site-packages\snooty\parser.py", line 1578, in build
    self._project.build(max_workers, postprocess)
  File "C:\Users\********\AppData\Roaming\Python\Python39\site-packages\snooty\parser.py", line 1351, in build
    for page, diagnostics in results:
  File "C:\Users\********\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 870, in next
    raise value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 37: invalid start byte
[Error - 10:50:25 AM] Server initialization failed.
  Message: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 37: invalid start byte
  Code: -32602 
[object Object]
[Error - 10:50:25 AM] Starting client failed
  Message: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 37: invalid start byte
  Code: -32602 
[object Object]
```

I thought maybe the `HEAD` reference was due to my `config.py` looking for the tag, which my current project does not have:

``` python3
# Get 0.0.0 version from latest Git tag
version = None
try:
    tagcmd = "git describe --tags --abbrev=0"
    version = subprocess.check_output(tagcmd, shell=True).decode().strip()
except:
    pass
if not version or version == "":
    version = "0.0.0"
```

Even though that `try/except` should capture any errors, I commented it out and defined `version = "0.0.0"` but the error persists upon re-opening the project.

**Comment by lbussy** [comment]
Anybody?

![image](https://user-images.githubusercontent.com/9092188/122689360-9efd8f00-d1e7-11eb-99be-914b0a81cfd6.png)

**Comment by malcolm061990** [comment]
Is anybody here? The same error
